@startuml

' 类图

class 用户 {
    ID
    姓名
    密码
    身份（经理/主管/员工）
    所属部门
    排班类型
}

class 人脸信息 {
    ID
    用户ID
    人脸信息
    状态（待审批/可用/废弃）
}

class 排班 {
    ID
    用户ID
    开始时间
    结束时间
    排班类型（正常/加班）
    状态（未签到/已签到/请假）
}

class 签到记录 {
    ID
    排班ID
    签到时间
    签退时间
}

class 请假记录 {
    ID
    用户ID
    开始时间
    结束时间
    请假理由
    状态（待审批/通过审批/驳回）
}

class 加班申请 {
    ID
    用户ID
    加班理由
    开始时间
    结束时间
    状态（待审批/通过审批/驳回）

}

class 工时 {
    ID
    用户ID
    日期
    工时
}

用户 "1" -- "*" 排班 : 参与排班
用户 "1" -- "*" 请假记录 : 请假
用户 "1" -- "*" 加班申请 : 申请
用户 "1" -- "*" 人脸信息 : 拥有
排班 "1" -- "0..1" 签到记录 : 对应
用户 "1" -- "*" 工时 : 拥有

@enduml