@startuml

' 类图

class 用户 {
    ID
    姓名
    密码
    身份（经理/主管/员工）
    所属部门
    排班类型

    添加用户信息()
    删除用户信息()
    修改用户信息()
    任用主管()
    罢免主管()

}

class 人脸信息 {
    ID
    用户ID
    人脸信息
    状态（待审批/可用/废弃）

    导入人脸信息()
    修改人脸信息()
    废弃人脸信息()
}

class 排班 {
    ID
    用户ID
    开始时间
    结束时间
    排班类型（正常/加班）
    状态（未签到/已签到/请假）
    
    查看工作班次()
    调整工作班次()
}

class 签到记录 {
    ID
    排班ID
    签到时间
    签退时间

    考勤打卡()
}

class 请假记录 {
    ID
    用户ID
    开始时间
    结束时间
    请假理由
    状态（待审批/通过审批/驳回）

    审批()
    销假()
}

class 加班申请 {
    ID
    用户ID
    加班理由
    开始时间
    结束时间
    状态（待审批/通过审批/驳回）

    审批加班()
}

class 工时 {
    ID
    用户ID
    日期
    工时

    添加工时()
    查看上班情况()
}

class 临时加班 {
    ID
    发起人ID
    开始时间
    结束时间
    状态（已发布/已结束）
}

class 临时加班记录 {
    ID
    临时加班ID
    参与者ID
    状态（报名成功/参与成功/参与失败）

    成功打卡()
}

用户 "1" -- "*" 排班 : 参与排班
用户 "1" -- "*" 请假记录 : 请假
用户 "1" -- "*" 加班申请 : 申请
用户 "1" -- "*" 人脸信息 : 拥有
排班 "1" -- "0..1" 签到记录 : 对应
用户 "1" -- "*" 工时 : 拥有

用户 "*" -- "*" 临时加班 : 创建
用户 "*" -- "*" 临时加班记录 : 参与临时加班
临时加班 "1" -- "*" 临时加班记录 : 参与记录

' 用户 .> 排班 : 查看上班情况
' 用户 .> 请假记录 : 审批请假记录
' 用户 .> 加班申请 : 审批加班申请
' 签到记录 .> 临时加班记录 : 确认打卡
' 签到记录 .> 工时 : 添加工时

@enduml