@startuml

' 用例图代码

left to right direction
actor 员工
actor 经理
actor 部门主管

rectangle 系统 {
    ' 经理
    经理 -- (添加用户信息)
    经理 -- (删除用户信息)
    经理 -- (管理用户信息)
    经理 -- (任免主管)
    经理 -- (查看工作班次安排)
    经理 -- (创建全单位临时加班活动)
    经理 -- (查看所有员工上班情况)
    
    ' 部门主管
    (安排工作班次) -- 部门主管
    (查看工作班次安排) -- 部门主管
    (调整工作班次安排) -- 部门主管
    (审批请假) -- 部门主管
    (审批请假) .> (调整工作班次安排) : <<include>>
    (审批加班) -- 部门主管
    (查看本部门员工上班情况) -- 部门主管

    ' 员工
    员工 -- (查看工作班次安排)
    员工 -- (请假)
    (请假) .> (提醒主管) : <<include>>
    员工 -- (销假)
    员工 -- (记录考勤)
    员工 -- (申请加班)
    (申请加班) .> (记录考勤) : <<extend>>
    员工 -- (查看上班情况)
    员工 -- (更新账户信息)

    员工 -- (参加临时性加班)
    (参加临时性加班) --> (记录考勤) : <<include>>、
}

@enduml